# Generated by Django 3.0 on 2020-10-07 15:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20201007_2150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='slug_product',
            field=models.SlugField(default=uuid.uuid1, unique=True, verbose_name='URL'),
        ),
    ]
